name: Release
on:
  release:
    types: [created]
  push:
    tags: ["*"]
jobs:
  releases:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.37
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
        binary_name: aws-dynamodb-cache-lambda-extension
        extra_files: README.md
