name: Release
permissions:
  contents: write
  packages: write
on:
  release:
    types: [created]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - uses: wangyoucao577/go-release-action@v1.37
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
        extra_files: README.md
        build_command: make build
